# For local phase configurations
#application:
#  name: financial-statistics-batch


spring:
  datasource:
    url: jdbc:mysql://shop.voyagerss.com:3306/fn_statistic?characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: fn
    password: dugodwk1
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: fn
      password: dugodwk1
      jdbc-url: jdbc:mysql://shop.voyagerss.com:3306/fn_statistic?characterEncoding=utf8&serverTimezone=UTC
  #    jpa:
#      show-sql: true
#      generate-ddl: true
#      hibernate:
#        ddl-auto: none
#      properties:
#        hibernate:
#          format_sql: true
#          dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    mongodb:
      host: mongodb://fn:dugodwk1@shop.voyagerss.com/fn?serverSelectionTimeoutMS=5000&connectTimeoutMS=10000
      database: fn
      authentication-database: admin
      username: fn
      password: dugodwk1
#  batch:
#    job:
#      enabled: on

#  devtools:
#    livereload:
#      enabled: true
#  mvc:
#    throw-exception-if-no-handler-found: true

#  batch:
#    job:
#      enabled: true
#      names: ${job.name:NONE}
#    initialize-schema: never

#app:
ecos-api-key: A3KS6JOGXDYWDBC2XQ3Y
