# For local phase configurations
application:
  name: financial-statistics-service
server:
  port: 54000

spring:
  datasource:
    #        driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://shop.voyagerss.com:3306/fn_statistic?characterEncoding=utf8&serverTimezone=UTC
    username: fn-service
    password: dugodwk1
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: none
      naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
  #    autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      host: mongodb+srv://fn-service:dugodwk1@shop.voyagerss.com/main?authSource=admin&retryWrites=true
      database: fn-statistic
      authentication-database: admin
      username: fn-service
      password: dugodwk1
---
spring:
  config:
    activate:
      on-profile: local


---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    hibernate:
      ddl-auto: update


#OAuth2
encodeKey: secret
#Email account info
email.account: en9door
email.password: dbstnr7079&
#REST API
kakao.client.id: e32a4d819f76b2ca4e652a2477ecf982
#kakao pay
kakao.admin.key: 9182554bcd6244da75828cfed4e62a65

krbank:
  apikey: A3KS6JOGXDYWDBC2XQ3Y
file:
  upload-dir: C:\ftp
